### ISSUE TITLE
Setup cloud for NLP bank statements data

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER_with_preprocess#3]
1. Set up the virtual environment: this was started by Alejo and finished by Neeraj today
2. Move data to the extraction VM: 23.99.106.54:
The data from Alejo's user was moved from the OSL original server (20.49.195.33). We are waiting Pardeep answer tomorrow to finish moving the data and Mehar's one about dataset description to check that all the dataset has been collected

**Comment by neerajvashistha** [comment]
Where are we on this, "Move data to the extraction VM" ? 
**Required**: The source server details with path, what data is to be moved, the destination server details with path.
